/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author facue
 */
public class allPokemonsModifyEvolution extends javax.swing.JInternalFrame {
    private Controlador controlador;

    public JTable getTableEvoType() {
        return tableEvoType;
    }

    public JLabel getLblName() {
        return lblName;
    }

    public void setLblName(JLabel lblName) {
        this.lblName = lblName;
    }

    public JTextField getTxtNewName() {
        return txtNewName;
    }

    public void setTxtNewName(JTextField txtNewName) {
        this.txtNewName = txtNewName;
    }

    public void setTableEvoType(JTable tableEvoType) {
        this.tableEvoType = tableEvoType;
    }

    public Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    /**
     * Creates new form allPokemonsModifyEvolution
     */
    public allPokemonsModifyEvolution() {
        this.setTitle("Modify Evolution");
        initComponents();
    }

    public JButton getBtnChange() {
        return btnChange;
    }

    public void setBtnChange(JButton btnChange) {
        this.btnChange = btnChange;
    }

    public JTable getTableAbilitiesEvo() {
        return tableAbilitiesEvo;
    }

    public void setTableAbilitiesEvo(JTable tableAbilitiesEvo) {
        this.tableAbilitiesEvo = tableAbilitiesEvo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEvoType = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNewName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAbilitiesEvo = new javax.swing.JTable();
        btnAddTypeEvo = new javax.swing.JButton();
        btnRemoveType = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);

        tableEvoType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        tableEvoType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEvoTypeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEvoType);

        jLabel1.setText("Name:");

        lblName.setText("lblName");

        jLabel2.setText("Type/s");

        jLabel3.setText("New name");

        btnChange.setText("Change evolution name");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        jLabel4.setText("Abilitie/s");

        tableAbilitiesEvo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        tableAbilitiesEvo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAbilitiesEvoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableAbilitiesEvo);

        btnAddTypeEvo.setText("Add type");
        btnAddTypeEvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTypeEvoActionPerformed(evt);
            }
        });

        btnRemoveType.setText("Remove selected type");
        btnRemoveType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveTypeActionPerformed(evt);
            }
        });

        jButton1.setText("Add abilitie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove selected abilitie");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChange))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddTypeEvo)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemoveType))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblName)
                    .addComponent(jLabel3)
                    .addComponent(txtNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChange)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTypeEvo)
                    .addComponent(btnRemoveType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        controlador.getModelo().changeEvolutionName(controlador.getModelo().getAuxEvo().getId());
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnAddTypeEvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTypeEvoActionPerformed
        if (!controlador.getAllPokemonsAddTypeEvo().isVisible())
        {
        controlador.getAllPokemonsAddTypeEvo().setVisible(true);
        controlador.getPrincipal().getDesktop().add(controlador.getAllPokemonsAddTypeEvo(),0);
        controlador.getModelo().btnTypesEvo();
        }
    }//GEN-LAST:event_btnAddTypeEvoActionPerformed

    private void tableEvoTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEvoTypeMouseClicked
    int fila = tableEvoType.getSelectedRow();
    if (fila==-1)
    {
        JOptionPane.showMessageDialog(null, "Error");
    }
    else
    {
        String name = tableEvoType.getValueAt(fila,0).toString();
        controlador.getModelo().setAuxType(controlador.getModelo().createTypeObject(name));
        System.out.println(controlador.getModelo().getAuxType().getName());
    }        
    }//GEN-LAST:event_tableEvoTypeMouseClicked

    private void btnRemoveTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveTypeActionPerformed
       if (controlador.getModelo().removeTypeEvo(controlador.getModelo().getAuxType().getId()))
       {
           JOptionPane.showMessageDialog(null, "Removed");
       }
    }//GEN-LAST:event_btnRemoveTypeActionPerformed

    private void tableAbilitiesEvoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAbilitiesEvoMouseClicked
      int fila = tableAbilitiesEvo.getSelectedRow();
    if (fila==-1)
    {
        JOptionPane.showMessageDialog(null, "Error");
    }
    else
    {
        String name = tableAbilitiesEvo.getValueAt(fila,0).toString();
        controlador.getModelo().setAuxAbi(controlador.getModelo().createObjectAbilities(name));
        controlador.getNewAbilitieEvo().dispose();
    }    
    }//GEN-LAST:event_tableAbilitiesEvoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!controlador.getNewAbilitieEvo().isVisible())
        {
            controlador.getNewAbilitieEvo().setVisible(true);
            controlador.getPrincipal().getDesktop().add(controlador.getNewAbilitieEvo(),0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(controlador.getModelo().removeAbilitieEvo(controlador.getModelo().getAuxEvo().getId(),controlador.getModelo().getAuxAbi().getId()))
       {
           JOptionPane.showMessageDialog(null, "Removed");
           controlador.getModelo().removeDatabaseAbilitie(controlador.getModelo().getAuxAbi().getId());
       }
    }//GEN-LAST:event_jButton2ActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTypeEvo;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnRemoveType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tableAbilitiesEvo;
    private javax.swing.JTable tableEvoType;
    private javax.swing.JTextField txtNewName;
    // End of variables declaration//GEN-END:variables
}
