/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author facue
 */
public class allPokemonsInfo extends javax.swing.JInternalFrame {

    private Controlador controlador;

    public Controlador getControlador() {
        return controlador;
    }

    public JTable getTableModifyAbilities() {
        return tableModifyAbilities;
    }

    public void setTableModifyAbilities(JTable tableModifyAbilities) {
        this.tableModifyAbilities = tableModifyAbilities;
    }

    public JTable getTableModifyEvolution() {
        return tableModifyEvolution;
    }

    public void setTableModifyEvolution(JTable tableModifyEvolution) {
        this.tableModifyEvolution = tableModifyEvolution;
    }

    public JTable getTableModifyType() {
        return tableModifyType;
    }

    public void setTableModifyType(JTable tableModifyType) {
        this.tableModifyType = tableModifyType;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    /**
     * Creates new form allPokemonsInfo
     */
    public allPokemonsInfo() {
        initComponents();
    }

    public JLabel getLblNameModify() {
        return lblNameModify;
    }

    public void setLblNameModify(JLabel lblNameModify) {
        this.lblNameModify = lblNameModify;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableModifyEvolution = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableModifyAbilities = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableModifyType = new javax.swing.JTable();
        lblNameModify = new javax.swing.JLabel();
        btnAddType = new javax.swing.JButton();
        btnRemoveType = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Name:");

        jLabel2.setText("Type/s");

        jLabel3.setText("Evolution/s");

        jLabel4.setText("Abilities");

        tableModifyEvolution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane1.setViewportView(tableModifyEvolution);

        tableModifyAbilities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableModifyAbilities);
        if (tableModifyAbilities.getColumnModel().getColumnCount() > 0) {
            tableModifyAbilities.getColumnModel().getColumn(0).setResizable(false);
        }

        tableModifyType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableModifyType);
        if (tableModifyType.getColumnModel().getColumnCount() > 0) {
            tableModifyType.getColumnModel().getColumn(0).setResizable(false);
        }

        lblNameModify.setText("jLabel5");

        btnAddType.setText("Add type");
        btnAddType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTypeActionPerformed(evt);
            }
        });

        btnRemoveType.setText("Remove selected type");
        btnRemoveType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblNameModify))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoveType)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNameModify))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddType)
                    .addComponent(btnRemoveType))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTypeActionPerformed
        if (!controlador.getAllPokemonsAddType().isVisible())
        {
           controlador.getAllPokemonsAddType().setVisible(true);
           controlador.getModelo().btnTypes();
           controlador.getPrincipal().getDesktop().add(controlador.getAllPokemonsAddType(),0);
        }
    }//GEN-LAST:event_btnAddTypeActionPerformed

    private void btnRemoveTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddType;
    private javax.swing.JButton btnRemoveType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNameModify;
    private javax.swing.JTable tableModifyAbilities;
    private javax.swing.JTable tableModifyEvolution;
    private javax.swing.JTable tableModifyType;
    // End of variables declaration//GEN-END:variables
}
