/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author facue
 */
public class newAbilitie extends javax.swing.JInternalFrame {
    private Controlador controlador;

    public Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    /**
     * Creates new form newPokemon
     */
    public newAbilitie() {
        initComponents();
        this.setTitle("New abilitie");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNewAbilitie = new javax.swing.JTextField();
        btnAddAbilitie = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Name:");

        txtNewAbilitie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewAbilitieActionPerformed(evt);
            }
        });

        btnAddAbilitie.setText("Add");
        btnAddAbilitie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAbilitieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddAbilitie)
                    .addComponent(txtNewAbilitie, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNewAbilitie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddAbilitie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAbilitieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAbilitieActionPerformed
        String name=controlador.getModelo().addAbilitie();
        System.out.println(name);
        int id= controlador.getModelo().getIdFromAbilitieName(name);
        System.out.println(id);  
        if (controlador.getModelo().addAbilitieToPokemon(id))
        {
            JOptionPane.showMessageDialog(null, "Evolution added");
            controlador.getNewAbilitie().getTxtNewAbilitie().setText(null);  
        }
    }//GEN-LAST:event_btnAddAbilitieActionPerformed

    private void txtNewAbilitieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewAbilitieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewAbilitieActionPerformed

    public JButton getBtnAddAbilitie() {
        return btnAddAbilitie;
    }

    public void setBtnAddAbilitie(JButton btnAddAbilitie) {
        this.btnAddAbilitie = btnAddAbilitie;
    }

    public JTextField getTxtNewAbilitie() {
        return txtNewAbilitie;
    }

    public void setTxtNewAbilitie(JTextField txtNewAbilitie) {
        this.txtNewAbilitie = txtNewAbilitie;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAbilitie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNewAbilitie;
    // End of variables declaration//GEN-END:variables
}
