/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author facue
 */
public class newEvolution extends javax.swing.JInternalFrame {
    private Controlador controlador;

    public Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public JButton getBtnAddEvo() {
        return btnAddEvo;
    }

    public void setBtnAddEvo(JButton btnAddEvo) {
        this.btnAddEvo = btnAddEvo;
    }

    public JTextField getTxtEvo() {
        return txtEvo;
    }

    public void setTxtEvo(JTextField txtEvo) {
        this.txtEvo = txtEvo;
    }


    /**
     * Creates new form newPokemon
     */
    public newEvolution() {
        initComponents();
        this.setTitle("New evolution");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEvo = new javax.swing.JTextField();
        btnAddEvo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtInputLvl = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setText("Name:");

        btnAddEvo.setText("Add");
        btnAddEvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEvoActionPerformed(evt);
            }
        });

        jLabel2.setText("Lvl Evolution:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddEvo)
                    .addComponent(txtEvo, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(txtInputLvl))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtInputLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnAddEvo))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEvoActionPerformed
        String name=controlador.getModelo().addEvolution();
        System.out.println(name);
        int id= controlador.getModelo().getIdFromEvolutionName(name);
        if (controlador.getModelo().addEvolutionToPokemon(id))
        {
            JOptionPane.showMessageDialog(null, "Evolution added");
            controlador.getNewEvolution().getTxtInputLvl().setText(null);
        }
    }//GEN-LAST:event_btnAddEvoActionPerformed

    public JTextField getTxtInputLvl() {
        return txtInputLvl;
    }

    public void setTxtInputLvl(JTextField txtInputLvl) {
        this.txtInputLvl = txtInputLvl;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEvo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtEvo;
    private javax.swing.JTextField txtInputLvl;
    // End of variables declaration//GEN-END:variables
}
