/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author facue
 */
public class newPokemon extends javax.swing.JInternalFrame {
    private Controlador controlador;

    public Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    /**
     * Creates new form newPokemon
     */
    public newPokemon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNewPkm = new javax.swing.JTextField();
        btnAddPkm = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Name:");

        btnAddPkm.setText("Add");
        btnAddPkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPkmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPkm)
                    .addComponent(txtNewPkm, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNewPkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddPkm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPkmActionPerformed
      if (controlador.getModelo().addPokemon())
      {
          JOptionPane.showMessageDialog(null, "Pokemon added");
      }
      else
      {
           JOptionPane.showMessageDialog(null, "Error");
      }
    }//GEN-LAST:event_btnAddPkmActionPerformed

    public JButton getBtnAddPkm() {
        return btnAddPkm;
    }

    public void setBtnAddPkm(JButton btnAddPkm) {
        this.btnAddPkm = btnAddPkm;
    }

    public JTextField getTxtNewPkm() {
        return txtNewPkm;
    }

    public void setTxtNewPkm(JTextField txtNewPkm) {
        this.txtNewPkm = txtNewPkm;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPkm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNewPkm;
    // End of variables declaration//GEN-END:variables
}
